# Generated by Django 5.0 on 2025-04-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_temporaryaccesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccesscode',
            name='code',
            field=models.CharField(help_text="Code d'accès temporaire", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='temporaryaccesscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création du code'),
        ),
        migrations.AlterField(
            model_name='temporaryaccesscode',
            name='expiration_date',
            field=models.DateTimeField(help_text="Date d'expiration du code"),
        ),
        migrations.AlterField(
            model_name='temporaryaccesscode',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_codes', to='users.professional'),
        ),
    ]
