# Generated by Django 5.0 on 2025-03-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_delete_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_sph', models.CharField(blank=True, max_length=10)),
                ('od_cyl', models.CharField(blank=True, max_length=10)),
                ('od_axe', models.CharField(blank=True, max_length=10)),
                ('og_sph', models.CharField(blank=True, max_length=10)),
                ('og_cyl', models.CharField(blank=True, max_length=10)),
                ('og_axe', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
