# Generated by Django 5.0 on 2025-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='od_dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='od_rc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='og_dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='og_rc',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
