# Generated by Django 5.0 on 2025-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_prescription_od_axe_lc_prescription_od_cyl_lc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='diabetique',
            field=models.BooleanField(default=False, verbose_name='Diabétique'),
        ),
    ]
