# Generated by Django 5.0 on 2025-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_medicalrecord_diabetique'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='keratoconique',
            field=models.BooleanField(default=False, verbose_name='Kératoconique'),
        ),
    ]
