# Generated by Django 5.0 on 2025-04-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_medicalrecord_keratoconique'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_details',
            field=models.TextField(blank=True),
        ),
    ]
