# Generated by Django 5.0 on 2025-04-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_prescription_prescription_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='cataracte',
            field=models.BooleanField(default=False, verbose_name='Cataracte'),
        ),
    ]
